### ISSUE TITLE
WFS 400 errors

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz#107]
Hi Baishan,

there are a lot of errors in the WFS logs like this: 

git-a6ac80b 2016/09/07 20:32:23 status: 400 serving /geonet/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geonet:quake_search_v1&outputFormat=json&sortBy=modificationtime&cql_filter=modificationtime%3E2016-08-25T11:30:10.8100Z%20AND%20eventtype=%27earthquake%27&maxFeatures=50

Is there something we need to change?

**Comment by bpeng** [comment]
this is caused by the extra parameter ```sortBy``` which is not currently supported, will add it.
