### ISSUE TITLE
Does geonet api have latest quake api?

### ISSUE THREAD

**Issue by pigflymoon** [GeoNet/haz#152]
Hi Team,
Do you have the api to get the latest quake api?
I only found  intensity api only returns mmi and coordinates not including  quake time.
and quake api such as  https://api.geonet.org.nz/quake?MMI=3, have to post mmi then return json data including coordinates and quake time. Is it any other ways to get a api which will return latest quake including coordinates and time? Thank you very much!

Cheers,

**Comment by junghao** [comment]
You can query https://api.geonet.org.nz/quake?MMI=0 then the first result is the latest quake .

**Comment by pigflymoon** [comment]
Thanks !! That's pretty cool! @junghao
