### ISSUE TITLE
Providing geohash4 for intensity_reported

### ISSUE THREAD

**Issue by sorennh** [GeoNet/haz#170]
Geohash4 is required for better map performance of felt reports. 

Steps 2, 3 & 4 need to be applied to prod DB in the given order:
- [x] (1) Update database DDL scripts (create table, function)
- [x] (2) Apply DDL changes to existing prod database 
- [x] (3) Run DML query to update current database
- [x] (4) Apply `NOT NULL` constraint to `geohash4` column
- [x] (5) Implement code in geonet-rest

**Comment by sorennh** [comment]
(1)

```
CREATE TABLE impact.intensity_reported (
	source TEXT NOT NULL,
	time TIMESTAMP WITH TIME ZONE NOT NULL,
	mmi int NOT NULL CONSTRAINT mmi_check CHECK (mmi >= 1 AND mmi <= 12),
	comment varchar(140) NOT NULL,
	geohash4 varchar(4) NOT NULL,
	geohash5 varchar(5) NOT NULL,
	geohash6 varchar(6) NOT NULL,
	location GEOGRAPHY(POINT, 4326) NOT NULL,
	UNIQUE (source, time)
);
```
```
BEGIN
INSERT INTO impact.intensity_reported(source, time, mmi, comment, geohash4, geohash5, geohash6, location)
VALUES (source_n, time_n, mmi_n, comment_n, st_geohash(loc, 4), st_geohash(loc, 5), st_geohash(loc, 6), loc);
RETURN;
EXCEPTION WHEN unique_violation THEN
--  Loop once more to see if a different insert happened after the update but before our insert.
tries = tries + 1;
if tries > 1 THEN
RETURN;
END IF;
END;
END LOOP;
END;
$$
LANGUAGE plpgsql;
```

**Comment by sorennh** [comment]
(2) **To be applied to prod database**

`ALTER TABLE impact.intensity_reported ADD COLUMN geohash4 character varying(4);`

```
update impact.intensity_reported
set geohash4 = st_geohash(location, 4)
```

**Comment by sorennh** [comment]
(3) **To be applied to prod database**

```
update impact.intensity_reported
set geohash4 = st_geohash(location, 4)
```

**Comment by sorennh** [comment]
(4) Will be provided with PR

**Comment by sorennh** [comment]
(5) Will be provided with PR

**Comment by gclitheroe** [comment]
lgtm except should this say ... varchar(4)... and not "varying"?

`ALTER TABLE impact.intensity_reported ADD COLUMN geohash4 character varying(4);`

**Comment by sorennh** [comment]
@gclitheroe The DB updates (2)-(4) are done on prod. Felt reports and maps are still working :-)

I will create the PR next with the API code changes (5).
