### ISSUE TITLE
API: /news/geonet returning links as 'http' rather than 'https'

### ISSUE THREAD

**Issue by danieldooley** [GeoNet/haz#190]
The links in the response of /news/geonet on the api returns links to the news stories but these links are for http rather than https, the default settings on iOS mean that we have to create an exception to load insecure pages. The news stories are available over https so it would be beneficial (as long as it doesn't cause issues elsewhere) to provide links as https

**Comment by sorennh** [comment]
Changed news URL to use https instead of http.
