### ISSUE TITLE
Notification message change for GeoNet Quake

### ISSUE THREAD

**Issue by kfenaugh** [GeoNet/haz#40]
As the new GeoNet Quake apps have been rolled out, we need to change the notification message to use the "shaking" concepts introduced in the app. I propose (for example):

**M4.4 quake causing light shaking near New Plymouth**

as the format. This gives the size of the earthquake (for those with mag/dep rules) and its impact on people (for those with shaking rules).

**Comment by gclitheroe** [comment]
After discussion with Caroline and Kev we've agreed the push notification for All localities should use MMI at a distance.

I will check what makes the most sense to go with the Twitter message.
