### ISSUE TITLE
Convert geonet-rest to use *result etc

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz#51]
Hi Howard,

please could you apply the same toHandler approach from origin to geonet-rest?  You can remove all the use of web and header and so the gzip handler as well.

I will decide with @quiffman if we keep gzipping in the app or push it out to Fastly.

Thanks,
Geoff

**Comment by junghao** [comment]
I think gzip handler is quite useful for fetching felt report data for mobile app.

**Comment by junghao** [comment]
We don't have to provide HTML error pages, right?

**Comment by gclitheroe** [comment]
We would still gzip the content but in the Fastly cache, out in front of this application.  Fastly does a smarter job.  

Yes - just error codes, no need for pages.
