### ISSUE TITLE
wfs and quakesearch deploy

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz#74]
These are ready to build and deploy.

- [x] check extra regions in the DB
- [x] read only DB slave
- [x] quay repo for wfs
- [x] quay repo for quakesearch 
- [x] final review
- [x] app security fixes
- [x] build containers in travis.
- [x] wfs beanstalk app 
- [x] quakesearch deploy
- [x] delete and back fill DB with updated seiscompml
- [x] delete and back fill S3 with updated seiscompml
- [x] dns repoints
- [x] https with *geonet cert
- [x] Assign tier (2 I think)
- [x] run books
- [x] probing
- [x] delete jobs from snap-ci

Check the regions in the db first.
Read only DB slave?

**Comment by gclitheroe** [comment]
@bpeng @kfenaugh @carolinelittle 

the new (Go) version of quakesearch is up, running against a read only replica of the api.geonet.org.nz DB.  Please could you check out that's it equivalent enough to quakesearch.geonet.org.nz that  I can get the DNS repointed and do the https config?  Please log changes not to do with the redeployment in new issues thanks.

http://quakesearch-env.ap-southeast-2.elasticbeanstalk.com/

- [ ]  yes - it's all good, repoint the DNS.

**Comment by carolinelittle** [comment]
Seems good to me. Though, geez, I specifically chose those colours so that they'd look good on the map quest maps. If we change to google maybe they'd need some tweeking!

**Comment by kfenaugh** [comment]
No quakes are being returned with negative longitude in the new version.  I ran a query close to the 180 meridian.

5 (all positive) in

http://quakesearch-env.ap-southeast-2.elasticbeanstalk.com/csv?bbox=179.95,-49,183,-32&startdate=2016-01-01T0:00:00&enddate=2016-8-24T3:00:00

157 (the above 5, and the rest with negative longitude) in:

http://quakesearch.geonet.org.nz/services/1.0.0/csv?bbox=179.95,-49,183,-32&startdate=2016-01-01T0:00:00&enddate=2016-8-24T3:00:00

**Comment by gclitheroe** [comment]
@bpeng @carolinelittle @kfenaugh 

the Go version of the wfs is up.  Pretty similar deal to quaksearch above.  Thanks!

http://wfs-env.ap-southeast-2.elasticbeanstalk.com/

- [ ] yes - it's all good, repoint the DNS.

**Comment by gclitheroe** [comment]
@kfenaugh - Baishan made a bug fix for quakesearch and I've deployed it.  Please could you see if that's done the trick?

**Comment by kfenaugh** [comment]
Ok, the quakesearch bug is fixed okay, thanks @bpeng . The only differences left were all quakes that have a depth of 0km.  Sigh! So I'm good to go with "Quakesearch Go!"

I am planning to have a look at the wfs next.

**Comment by kfenaugh** [comment]
WFS queries look good to me. Two small things (not show-stoppers for this exercise):

- The output precision of the floats in the CSV file are 17 decimals - 8 would be ample.
- The header line in the CSV file has spaces that could be removed for tidiness - in front of the words " latitude, magnitude, depth".

**Comment by carolinelittle** [comment]
Someone's emailed in with this quake webpage: http://www.geonet.org.nz/quakes/region/canterbury/2011a440804

There are a few odd things. It's an unreviewed Seiscomp solution of the Chch June 2011 quake, when the correct soln is the cusp one. Also, it has the wrong year - 2016.
(correct soln: http://www.geonet.org.nz/quakes/3528839)

I don't know how he found the quake, it does not come up when querying with quakesearch. I'm assuming it's an issue with what you've all done? Let me know if you'd like to know how the user found the quake.

**Comment by kfenaugh** [comment]
@carolinelittle - This shows it up https://www.geonet.org.nz/quakes/region/canterbury/felt/severe

**Comment by carolinelittle** [comment]
Oh dear, that's not cool.

**Comment by kfenaugh** [comment]
I can only guess as to how this event is appearing. The format of public id with "a" in it isn't current.

@gclitheroe , could you delete the entry in the www db for 2011a440804? Also see if there are any public ids of the form "2011x....."  that pre-date 2012? Hopefully a one-off.

**Comment by gclitheroe** [comment]
'a' was avalon for a while (might still be?).  Will take a look.

**Comment by gclitheroe** [comment]
should be gone.  Looks like our testing data set had gone into the DB for www.geonet.org.nz at somepoint during rebuilding it.  Apologies!

the wfs and quakesearch DB is fine.

**Comment by kfenaugh** [comment]
Thanks, Geoff! It's gone.
