### ISSUE TITLE
quakesearch GeoJSON valid?

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz#75]
Hi Baishan,

I had a query from Ian Matcham at lunch time about the GeoJSON from the current quakesearch - he says it's not valid and it doesn't seem to be to me.

I tested it here http://geojsonlint.com/ and it doesn't validate.  

He thought there was an issue with the CRS definition.  There may be others.

Please can you test the Go version and fix if needed?   Also the Go version of the WFS? If it take us long time to get it deployed we may need to back port it to the old one as well.

You can also post to geojsonlint to test from code http://geojason.info/2012/geojson-validation-via-geojsonlint.com/

Thanks,
Geoff

/cc @kfenaugh

**Comment by bpeng** [comment]
@gclitheroe The GO version projects (quakesearch and wfs) don't have the CRS definition in the JSON output.
