### ISSUE TITLE
wfs, quakesearch  - SQL injection

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz#77]
wfs and quakesearch need some work before I deploy them.  

The most concerning thing is the possibility of SQL injection.  For a DB query it's best to used Query or QueryRow with placeholders and pass them as args to the query.

If you're going to build the query string yourself then you need to sanitise the query parameters from the URL (from the user) very carefully.

I can see why you build the query this way.  Up to you to come up with the best solution.

Take a look here for what sql injection can look like https://github.com/mpirnat/lets-be-bad-guys/blob/master/solutions.md

/cc @junghao

**Comment by gclitheroe** [comment]
You might find it useful to look at https://github.com/lib/pq/blob/master/encode.go especially https://github.com/lib/pq/blob/master/encode.go#L145

**Comment by bpeng** [comment]
@gclitheroe As the number of query parameters are uncertain, it's difficult to use placeholders in the sql, there could be many combinations.

SQL injection may not be a problem as this is a read only database, and data is public.

In ```quakesearch```, query parameters are currently checked against a predefined set of parameters, invalid parameters are simply ignored, this should be replaced by a response of BadRequest.

In ```wfs```, query parameters in CQL are not validated yet, these should be validated against the fields in the database.

**Comment by gclitheroe** [comment]
Yes - I understand it's a bit of a tricky problem (I guessed it would be when you started).

I think the accepted answer here should help with a placeholder approach

http://stackoverflow.com/questions/20271123/how-to-execute-an-in-lookup-in-sql-using-golang

You should be able to build the query string, adding numbered placeholders as you go (with some counter for the next paramter $n) and keeping a slice of the params to pass.
